name: Quality

on:
  push:
    branches:
      - main
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:



  composer:
    runs-on: ubuntu-22.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v6
      - name: 🪄 Setup
        uses: ./.github/actions/setup
      - name: 🕵️‍♂️ Run Composer Validate
        run: composer validate
      - name: 🕵️‍♂️ Run Composer Audit
        run: composer audit
